odri/robot_interface:
  ros__parameters:
    robot_yaml_name: "flying_arm_2.yaml"
    n_slaves: 1
    # safe_configuration [-1.0, 2.8]
    safe_configuration: [-1.4, 2.8]
    safe_torque: 1.0
    safe_kp: 0.5
    safe_kd: 6.0
    safe_current: 5.0
    joint_names: ["flying_arm_2__j_bl_link1", "flying_arm_2__j_link1_link2"]

